library(shellpipes)
manageConflicts()

library(ggplot2); theme_set(theme_bw(base_size=15))
startGraphics()

loadEnvironments()

print(ggplot(epi)
	+ aes(t, I)
	+ geom_line()
	+ ylab("Active cases")
)
print(ggplot(epi)
	+ aes(t, rho)
	+ geom_line()
	+ ylab("Inclination to test")
)
print(ggplot(epi)
	+ aes(t, pos)
	+ geom_line()
	+ geom_line(aes(y=pos+neg), lty=2)
	+ ylab("Tests")
)
print(ggplot(epi)
	+ aes(t, pp)
	+ geom_line()
	+ ylab("Positivity")
)

